### ISSUE TITLE
Problem using code in text.py

### ISSUE THREAD

**Issue by Cristiano1997** [gusanthon/pywdf#4]
Hi, I tried to run the test program and encoutered 2 warning;

The first concerns line 4 mk2_sef = RCA_MK2_SEF(44100, 0, 3000) #for high_pass_cutoff=0, but it work for high_pass_cutoff=1

the second is i line 6 mk2_sef.plot_freqz_list(positions, mk2_sef.set_lowpass_knob_position, param_label = 'lpf knob pos', 
                                outpath='pywdf/figures/mk2_sef_lpf_knob.png')

traceback (most recent call last):
File: "file location", line 6, mk2_sef.plot_freqz_list(positions, mk2_sef.set_lowpass_knob_position, param_label = 'lpf knob pos', 
outpath='pywdf/figures/mk2_sef_lpf_knob.png') attribute 'set_lowpass_knob_position'

Pressing Ctrl+click on "RCA_MK2_SEF(44100, 0, 3000)" and exploring the class, I couldn't find "lowpass_knob_position" anywhere;
what went wrong?

Thanks for your patience

**Comment by gusanthon** [comment]
Hey Cristiano, thanks for bringing this up. This happened because I was in the middle of refactoring the RCA_MK2_SEF class, but unfortunately, I got sidetracked and haven't been able to finish it yet. I'll make it a priority to wrap up those changes as soon as possible. In the meantime, the rest of the library should still be fully operational. Thanks for your patience!

**Comment by Cristiano1997** [comment]
Ok, thanks for your commitment

**Comment by gusanthon** [comment]
this should be fixed with ab05d4fc21a3960883694901756b44875c15d849
